import {describe,it,expect} from 'vitest';
import {createMemoryAccessStore,effectivePlan,effectiveRole} from '../server/lib/access';
const owners=new Set(['owner']),reason='Test access change',role=(requestId:string,value:'admin'|'member',expectedVersion=0)=>({requestId,expectedVersion,kind:'role' as const,role:value,reason}),gift=(requestId:string,days:number,expectedVersion=0)=>({requestId,expectedVersion,kind:'gift' as const,days,reason});
describe('administrative access',()=>{
 it('derives owner from server IDs and permits delegated administration',async()=>{const s=createMemoryAccessStore();expect(effectiveRole('owner',await s.get('owner'),owners)).toBe('owner');expect(effectivePlan('free','owner',await s.get('owner'),owners)).toBe('pro');const a=await s.change('owner','admin',role('r1','admin'),owners);expect(effectivePlan('free','admin',a,owners)).toBe('pro');expect((await s.change('admin','next',role('r2','admin'),owners)).role).toBe('admin');});
 it('expires gifts exactly and preserves paid plans',async()=>{let now=100000;const s=createMemoryAccessStore(()=>now),a=await s.change('owner','reader',gift('g1',10),owners);now+=86400000;const b=await s.change('owner','reader',gift('g2',2,1),owners);expect(b.giftUntil).toBe(now+2*86400000);expect(b.giftUntil).toBeLessThan(a.giftUntil);expect(effectivePlan('free','reader',b,owners,b.giftUntil-1)).toBe('pro');expect(effectivePlan('free','reader',b,owners,b.giftUntil)).toBe('free');expect(effectivePlan('pro','reader',b,owners,b.giftUntil)).toBe('pro');expect(effectivePlan('lifetime','reader',b,owners,b.giftUntil)).toBe('lifetime');});
 it('refuses members, self changes and owner targets',async()=>{const s=createMemoryAccessStore();await expect(s.change('reader','other',gift('x',1),owners)).rejects.toMatchObject({status:403});await s.change('owner','admin',role('a','admin'),owners);for(const target of ['admin','owner'])await expect(s.change('admin',target,gift('b'+target,1),owners)).rejects.toMatchObject({code:'protected_access_target'});expect(await s.audit()).toHaveLength(1);});
 it('accepts only one simultaneous stale-version change',async()=>{const s=createMemoryAccessStore(),r=await Promise.allSettled([s.change('owner','reader',gift('a',1),owners),s.change('owner','reader',gift('b',2),owners)]);expect(r.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect((r.find(x=>x.status==='rejected') as PromiseRejectedResult).reason.code).toBe('access_version_conflict');expect(await s.audit()).toHaveLength(1);});
 it('replays without restoring a revoked gift and rejects changed payloads',async()=>{const s=createMemoryAccessStore(),req=gift('a',1),first=await s.change('owner','reader',req,owners);await s.change('owner','reader',gift('b',0,1),owners);expect(await s.change('owner','reader',req,owners)).toEqual(first);expect((await s.get('reader')).giftUntil).toBe(0);await expect(s.change('owner','reader',{...req,days:2},owners)).rejects.toMatchObject({code:'idempotency_conflict'});expect(await s.audit()).toHaveLength(2);});
 it('rechecks current role before replay',async()=>{const s=createMemoryAccessStore();await s.change('owner','admin',role('a','admin'),owners);const req=gift('g',1);await s.change('admin','reader',req,owners);await s.change('owner','admin',role('b','member',1),owners);await expect(s.change('admin','reader',req,owners)).rejects.toMatchObject({code:'admin_required'});});
 it('checks queued session validity after acquiring the mutex',async()=>{const s=createMemoryAccessStore();let release!:()=>void,entered!:()=>void,valid=true;const gate=new Promise<void>(r=>release=r),started=new Promise<void>(r=>entered=r);const blocker=s.change('owner','a',gift('a',1),owners,async()=>{entered();await gate;return true;});await started;const next=s.change('owner','b',gift('b',1),owners,async()=>valid);const rejection=expect(next).rejects.toMatchObject({code:'actor_session_invalid'});valid=false;release();await blocker;await rejection;expect((await s.get('b')).version).toBe(0);});
 it('returns copies and retains idempotence beyond the 50 displayed audit entries',async()=>{const s=createMemoryAccessStore(),request=gift('g0',1),first=await s.change('owner','reader',request,owners);first.role='admin';expect((await s.get('reader')).role).toBe('member');for(let i=1;i<55;i++)await s.change('owner','reader',gift('g'+i,1,i),owners);const audit=await s.audit();expect(audit).toHaveLength(50);audit[0].after.role='admin';expect((await s.get('reader')).role).toBe('member');await s.change('owner','reader',request,owners);expect((await s.get('reader')).version).toBe(55);});
 it.each([-1,0.5,367,NaN,Infinity])('rejects invalid duration %s',async days=>{const s=createMemoryAccessStore();await expect(s.change('owner','reader',gift('x',days),owners)).rejects.toMatchObject({status:400});expect(await s.audit()).toHaveLength(0);});
});

