import {beforeEach,afterEach,it,expect} from 'vitest';
import express from 'express';import type {Server} from 'node:http';import {randomUUID} from 'node:crypto';
import {createApiRouter} from '../server/api';import {createStore,type Store} from '../server/lib/store';import {createMemoryAccessStore} from '../server/lib/access';import {hashPassword} from '../server/lib/crypto';
let server:Server,base:string,store:Store;const password='synthetic-admin-password';
beforeEach(async()=>{store=createStore();for(const id of ['owner','admin','reader'])await store.createUser({id,email:id+'@example.test',passwordHash:hashPassword(password),plan:'free',createdAt:1});const app=express();app.use('/api',createApiRouter(store,createMemoryAccessStore(),new Set(['owner'])));await new Promise<void>(r=>server=app.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+(server.address() as any).port+'/api';});
afterEach(async()=>{await new Promise<void>(r=>server.close(()=>r()));});
const call=(path:string,token?:string,body?:any)=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});
const login=async(id:string)=>(await(await call('/auth/login',undefined,{email:id+'@example.test',password})).json());
const change=(targetId:string,more:any={})=>({targetId,requestId:randomUUID(),expectedVersion:0,kind:'gift',days:30,reason:'Customer goodwill',current:password,...more});
it('uses server identity and refuses anonymous, member and forged admin fields',async()=>{expect((await call('/admin/me')).status).toBe(401);const reader=await login('reader');expect((await call('/admin/lookup',reader.token,{email:'owner@example.test'})).status).toBe(403);const signup=await(await call('/auth/signup',undefined,{email:'new@example.test',password,role:'admin',plan:'pro'})).json();expect(signup.user.role).toBe('member');expect(signup.user.plan).toBe('free');const owner=await login('owner');expect(owner.user.role).toBe('owner');expect(owner.user.plan).toBe('pro');const lookup=await(await call('/admin/lookup',owner.token,{email:'reader@example.test'})).json();expect(lookup.user.passwordHash).toBeUndefined();expect(lookup.user.id).toBe('reader');});
it('requires reauthentication and grants expiring access without changing billed plan',async()=>{const owner=await login('owner'),reader=await login('reader');expect((await call('/admin/access',owner.token,change('reader',{current:'wrong'}))).status).toBe(401);const req=change('reader'),gift=await call('/admin/access',owner.token,req);expect(gift.status).toBe(200);expect((await(await call('/license',reader.token)).json()).plan).toBe('pro');expect((await store.getUserById('reader'))!.plan).toBe('free');expect((await call('/admin/access',owner.token,req)).status).toBe(200);expect((await(await call('/admin/audit',owner.token)).json()).events).toHaveLength(1);expect((await call('/admin/access',owner.token,change('reader',{days:0,expectedVersion:1}))).status).toBe(200);expect((await(await call('/license',reader.token)).json()).plan).toBe('free');expect((await call('/admin/access',owner.token,req)).status).toBe(200);expect((await(await call('/license',reader.token)).json()).plan).toBe('free');});
it('delegates and revokes admin with existing sessions and protects the owner',async()=>{const owner=await login('owner'),admin=await login('admin');expect((await call('/admin/access',owner.token,change('admin',{kind:'role',days:undefined,role:'admin'}))).status).toBe(200);expect((await call('/admin/me',admin.token)).status).toBe(200);expect((await call('/admin/access',admin.token,change('owner',{kind:'role',days:undefined,role:'member'}))).status).toBe(403);expect((await call('/admin/access',owner.token,change('admin',{kind:'role',days:undefined,role:'member',expectedVersion:1}))).status).toBe(200);expect((await call('/admin/me',admin.token)).status).toBe(403);expect((await call('/auth/delete',owner.token,{current:password})).status).toBe(409);});
it('rejects stale versions and hostile unrecognized fields',async()=>{const owner=await login('owner');expect((await call('/admin/access',owner.token,change('reader',{billingPlan:'lifetime'}))).status).toBe(400);expect((await call('/admin/access',owner.token,change('reader',{days:367}))).status).toBe(400);expect((await call('/admin/access',owner.token,change('reader'))).status).toBe(200);expect((await call('/admin/access',owner.token,change('reader'))).status).toBe(409);});

