import {describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import {runInNewContext} from 'node:vm';
const script=readFileSync(new URL('../auto-translation.js',import.meta.url),'utf8'),KEY='yomu.translation.rules',PREFIX='yomu.translation.active.',ORIGIN='https://reader.example.com',PAGE=ORIGIN+'/chapter/1',RULE={enabled:true,target:'fr',source:'eng'};
function gate(){let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return{promise,resolve};}
function event(){const listeners:any[]=[];return{addListener:vi.fn((fn:any)=>listeners.push(fn)),emit:(...a:any[])=>listeners.forEach(fn=>fn(...a)),clear:()=>{listeners.length=0;}};}
function area(data:Record<string,any>){return{get:vi.fn(async(k:any)=>structuredClone(k==null?data:Object.fromEntries((Array.isArray(k)?k:[k]).map((key:string)=>[key,data[key]])))),set:vi.fn(async(v:any)=>{Object.assign(data,structuredClone(v));}),remove:vi.fn(async(k:any)=>{for(const key of Array.isArray(k)?k:[k])delete data[key];})};}
function fixture(){const local:Record<string,any>={},session:Record<string,any>={},grants=new Set([ORIGIN+'/*']),events={updated:event(),activated:event(),removed:event(),permissions:event()},tab={id:1,url:PAGE,status:'complete'},warn=vi.fn();const api={storage:{local:area(local),session:area(session)},permissions:{contains:vi.fn(async({origins}:any)=>origins.every((o:string)=>grants.has(o))),onRemoved:events.permissions},tabs:{get:vi.fn(async(id:number)=>{if(id!==1)throw Error('missing tab');return{...tab};}),query:vi.fn(async()=>[{...tab}]),sendMessage:vi.fn(async(..._args:any[])=>({ok:true,started:true})),onUpdated:events.updated,onActivated:events.activated,onRemoved:events.removed},scripting:{executeScript:vi.fn(async(o:any)=>[{documentId:'doc1',frameId:0,result:o.files?undefined:true}])}};function reload(){const ctx:any={chrome:api,URL,crypto:{randomUUID},console:{warn},setTimeout,clearTimeout};runInNewContext(script,ctx);return ctx.YomuAutoTranslation;}return{api,local,session,grants,events,warn,tab,reload,mod:reload()};}
const starts=(h:any)=>h.api.tabs.sendMessage.mock.calls.filter(([,m]:any[])=>m.type==='DASI_TRANSLATE');const reverts=(h:any)=>h.api.tabs.sendMessage.mock.calls.filter(([,m]:any[])=>m.type==='DASI_TRANSLATE_REVERT');
async function saveOnly(h:any){h.api.tabs.query.mockResolvedValueOnce([]);expect((await h.mod.setRule(ORIGIN,RULE)).ok).toBe(true);}
function pause(h:any){const entered=gate(),release=gate(),original=h.api.scripting.executeScript.getMockImplementation();h.api.scripting.executeScript.mockImplementation(async(o:any)=>{if(o.files){entered.resolve();await release.promise;}return original(o);});return{entered,release};}
describe('automatic translation',()=>{
 it('validates exact origins and every offered language',()=>{const h=fixture();expect(h.mod.normalizeOrigin('https://READER.example.com:443/path')).toBe(ORIGIN);for(const target of 'en fr es de it pt nl ru uk pl tr ar fa hi id vi th ja ko zh-CN zh-TW fil ms sv no da fi cs el he ro hu bg sr hr'.split(' '))expect(h.mod.normalizeRule(ORIGIN,{...RULE,target}).target).toBe(target);for(const source of ['','kor','jpn','chi_sim','eng','fra'])expect(h.mod.normalizeRule(ORIGIN,{...RULE,source}).source).toBe(source);expect(()=>h.mod.normalizeRule(ORIGIN,{...RULE,target:'invalid'})).toThrow();});
 it.each(['http://reader.example.com','https://127.0.0.1','https://169.254.169.254','https://0x7f000001','https://[::1]','https://localhost','https://reader.local','https://reader.internal','https://host.home.arpa','https://reader.example.com:8443','https://user:password@reader.example.com','https://*.example.com','file:///tmp/page','<all_urls>'])('rejects origin %s',value=>{expect(fixture().mod.normalizeOrigin(value)).toBeNull();});
 it('requires permission and does not write on refusal',async()=>{const h=fixture();h.grants.clear();expect(await h.mod.setRule(ORIGIN,RULE)).toMatchObject({ok:false,status:'permission_required'});expect(h.api.storage.local.set).not.toHaveBeenCalled();expect(starts(h)).toHaveLength(0);});
 it('deduplicates activation and load events for one document',async()=>{const h=fixture();await saveOnly(h);h.events.activated.emit({tabId:1});h.events.updated.emit(1,{status:'complete'},h.tab);await Promise.all([h.mod.start(1,PAGE),h.mod.start(1,PAGE)]);expect(starts(h)).toHaveLength(1);expect(starts(h)[0]).toEqual([1,{type:'DASI_TRANSLATE',lang:'fr',src:'eng'},{documentId:'doc1'}]);});
 it('stops an activation disabled during injection',async()=>{const h=fixture();await saveOnly(h);const g=pause(h),starting=h.mod.start(1,PAGE);await g.entered.promise;const disable=h.mod.setRule(ORIGIN,{enabled:false});await vi.waitFor(()=>expect(h.local[KEY]?.[ORIGIN]).toBeUndefined());g.release.resolve();await Promise.all([starting,disable]);expect(starts(h)).toHaveLength(0);expect(reverts(h).length).toBeGreaterThan(0);expect(h.session[PREFIX+'1']).toBeUndefined();});
 it('does not let an old disable stop a new enable',async()=>{const h=fixture();await saveOnly(h);const g=pause(h),old=h.mod.start(1,PAGE);await g.entered.promise;const disable=h.mod.setRule(ORIGIN,{enabled:false});await vi.waitFor(()=>expect(h.local[KEY]?.[ORIGIN]).toBeUndefined());const enable=h.mod.setRule(ORIGIN,{...RULE,target:'de'});await vi.waitFor(()=>expect(h.local[KEY]?.[ORIGIN]?.target).toBe('de'));g.release.resolve();await Promise.all([old,disable,enable]);expect(starts(h)).toHaveLength(1);expect(starts(h)[0][1].lang).toBe('de');expect(h.session[PREFIX+'1'].phase).toBe('active');const messages=h.api.tabs.sendMessage.mock.calls.map(([,m]:any[])=>m.type);expect(messages.slice(messages.lastIndexOf('DASI_TRANSLATE')+1)).not.toContain('DASI_TRANSLATE_REVERT');});
 it('stops on permission removal after worker restart',async()=>{const h=fixture();await h.mod.setRule(ORIGIN,RULE);Object.values(h.events).forEach(e=>e.clear());const resumed=h.reload();h.api.tabs.sendMessage.mockClear();h.grants.clear();h.events.permissions.emit({origins:[ORIGIN+'/*']});await vi.waitFor(()=>{expect(reverts(h).length).toBeGreaterThan(0);expect(h.session[PREFIX+'1']).toBeUndefined();});expect((await resumed.start(1,PAGE)).ok).toBe(false);expect(starts(h)).toHaveLength(0);});
 it('does not start after a navigation during injection',async()=>{const h=fixture();await saveOnly(h);const g=pause(h),start=h.mod.start(1,PAGE);await g.entered.promise;h.tab.url='https://other.example.com/';g.release.resolve();expect((await start).ok).toBe(false);expect(starts(h)).toHaveLength(0);});
 it('preserves rules on storage failures without logging private diagnostics',async()=>{const h=fixture();await saveOnly(h);const before=structuredClone(h.local);h.api.storage.local.get.mockRejectedValueOnce(Error('private https://secret.invalid'));expect(await h.mod.getRule(PAGE)).toMatchObject({ok:false,status:'storage_unavailable'});h.api.storage.local.set.mockRejectedValueOnce(Error('private https://secret.invalid'));expect((await h.mod.setRule(ORIGIN,{...RULE,target:'de'})).ok).toBe(false);expect(h.local).toEqual(before);expect(JSON.stringify(h.warn.mock.calls)).not.toContain('secret.invalid');});
});

