import {useEffect,useRef,useState} from "react";
import {Link} from "wouter";
import {AppHeader} from "@/components/AppHeader";
import {useI18n} from "@/i18n/I18nContext";
import {syncProvider} from "@/lib/sync";
type Account={id:string;email:string;role:string;plan:string;giftUntil:number;accessVersion:number};
export default function Admin(){
 const {lang}=useI18n(),fr=lang==="fr",say=(a:string,b:string)=>fr?a:b;
 const [actor,setActor]=useState<Account|null>(null),[target,setTarget]=useState<Account|null>(null),[events,setEvents]=useState<any[]>([]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[reason,setReason]=useState(""),[kind,setKind]=useState("gift"),[days,setDays]=useState(30),[role,setRole]=useState("admin"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const pending=useRef<{key:string;requestId:string}|null>(null);
 const explain=(e:unknown)=>{const code=e instanceof Error?e.message:"";return code==="access_version_conflict"?say("Ce compte a changé. Recherche-le à nouveau avant de confirmer.","This account changed. Look it up again before confirming."):code==="invalid_credentials"?say("Mot de passe incorrect.","Incorrect password."):code==="admin_required"||code==="unauthorized"?say("Connecte-toi avec un compte administrateur.","Sign in with an administrator account."):say("Action refusée ou service indisponible. Aucun succès n’est confirmé.","Action refused or service unavailable. Success is not confirmed.");};
 useEffect(()=>{let active=true;syncProvider.adminRequest("me").then(r=>{if(active)setActor(r.user);}).catch(e=>{if(active)setMessage(explain(e));});return()=>{active=false;};},[]);
 async function lookup(){setBusy(true);setTarget(null);pending.current=null;try{const r=await syncProvider.adminRequest("lookup",{email:email.trim()});setTarget(r.user);setMessage("");}catch(e){setMessage(explain(e));}finally{setBusy(false);}}
 async function refreshAudit(){try{setEvents((await syncProvider.adminRequest("audit")).events);}catch(e){setMessage(explain(e));}}
 async function apply(){
  if(!target||!password||reason.trim().length<3)return;
  const action=kind==="role"?say("Changer le rôle : ","Change role: ")+role:days===0?say("Retirer l’abonnement offert","Remove gifted access"):say("Offrir Pro pendant ","Gift Pro for ")+days+say(" jours à compter de maintenant"," days starting now");
  if(!window.confirm(action+"
"+target.email+"
"+say("Cela ne modifie ni ne résilie un abonnement payant existant.","This does not change or cancel an existing paid subscription.")))return;
  const change={targetId:target.id,expectedVersion:target.accessVersion,kind,...(kind==="role"?{role}:{days}),reason:reason.trim()};
  const key=JSON.stringify(change);if(pending.current?.key!==key)pending.current={key,requestId:crypto.randomUUID()};
  setBusy(true);
  try{await syncProvider.adminRequest("access",{...change,requestId:pending.current.requestId,current:password});setPassword("");pending.current=null;setTarget(null);setMessage(say("Modification enregistrée. Recherche le compte pour voir ses droits actuels.","Change saved. Look up the account to see its current access."));await refreshAudit();}catch(e){setMessage(explain(e));}finally{setBusy(false);}
 }
 return <div className="dasi-app"><AppHeader/><main className="dasi-main settings-main"><h1>{say("Administration","Administration")}</h1><p>{say("Droits d’accès et abonnements offerts. Les bibliothèques privées ne sont pas accessibles ici.","Access roles and gifted subscriptions. Private libraries are not accessible here.")}</p><p role="status" aria-live="polite">{message}</p>{!actor?<Link href="/settings">{say("Ouvrir mon compte","Open my account")}</Link>:<>
 <section className="settings-card"><h2>{say("Votre accès","Your access")}</h2><p>{actor.email} · {actor.role} · Pro {say("inclus sans paiement","included without payment")}</p><p>{say("Un administrateur peut nommer d’autres administrateurs. Le propriétaire défini sur le serveur reste protégé.","An administrator can appoint other administrators. The owner configured on the server remains protected.")}</p></section>
 <section className="settings-card"><h2>{say("Rechercher un compte","Find an account")}</h2><form className="auth-form" onSubmit={e=>{e.preventDefault();void lookup();}}><label>{say("Adresse e-mail exacte","Exact email address")}<input type="email" required maxLength={254} value={email} onChange={e=>{setEmail(e.target.value);setTarget(null);}}/></label><button className="primary-cta" disabled={busy}>{say("Rechercher","Find account")}</button></form></section>
 {target&&<section className="settings-card"><h2>{target.email}</h2><p>{say("Rôle","Role")}: {target.role} · {say("Offre active","Effective plan")}: {target.plan}</p><p>{say("Cadeau jusqu’au","Gift valid until")}: {target.giftUntil>Date.now()?new Date(target.giftUntil).toLocaleString():say("Aucun cadeau actif","No active gift")}</p>{target.id===actor.id||target.role==="owner"?<p>{say("Ce compte est protégé contre les modifications ici.","This account is protected from changes here.")}</p>:<form className="auth-form" onSubmit={e=>{e.preventDefault();void apply();}}><label>{say("Action","Action")}<select value={kind} onChange={e=>setKind(e.target.value)}><option value="gift">{say("Abonnement offert","Gifted subscription")}</option><option value="role">{say("Rôle administrateur","Administrator role")}</option></select></label>{kind==="gift"?<><label>{say("Nombre de jours (0 pour retirer)","Days (0 to remove)")}<input type="number" min={0} max={366} required value={days} onChange={e=>setDays(Number(e.target.value))}/></label><small>{say("Remplace la date de fin du cadeau. Les API externes restent soumises à leurs quotas et coûts.","Replaces the gift expiry date. External APIs still have usage limits and costs.")}</small></>:<label>{say("Nouveau rôle","New role")}<select value={role} onChange={e=>setRole(e.target.value)}><option value="admin">{say("Administrateur","Administrator")}</option><option value="member">{say("Membre","Member")}</option></select></label>}<label>{say("Motif pour le journal","Reason for the audit log")}<input required minLength={3} maxLength={200} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>{say("Votre mot de passe actuel","Your current password")}<input type="password" autoComplete="current-password" maxLength={1024} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary-cta" disabled={busy||reason.trim().length<3||!password}>{say("Vérifier et confirmer","Review and confirm")}</button></form>}</section>}
 <section className="settings-card"><h2>{say("Dernières opérations","Recent changes")}</h2><button className="ghost" onClick={refreshAudit}>{say("Actualiser le journal","Refresh audit log")}</button><ol>{events.map(e=><li key={e.requestId} style={{overflowWrap:"anywhere",marginBlock:12}}><strong>{new Date(e.at).toLocaleString()} · {e.kind==="gift"?say("Cadeau","Gift"):say("Rôle","Role")}</strong><p>{e.actorId} → {e.targetId}</p><p>{e.reason} · {e.kind==="gift"?(e.after.giftUntil?new Date(e.after.giftUntil).toLocaleString():say("Retiré","Removed")):e.after.role}</p></li>)}</ol></section>
 </>}</main></div>;
}

