/* Quiet Luxury Software: dark graphite surfaces, compact top navigation, high-contrast sans type, jade action accent, no paper/editorial nostalgia. */
import { useMemo, useState } from "react";
import { Bell, Bookmark, Check, ChevronDown, Clock3, Film, Library, Minus, MoreHorizontal, Play, Plus, RefreshCw, Search, Settings2, Sparkles, Trash2, Video, X } from "lucide-react";
import { toast } from "sonner";
const logo="/manus-storage/suivi-logo_b12e5dda.png";
type Item={id:number;title:string;meta:string;type:"Reading"|"Watching";progress:number;updated:string;source:string;accent:string;image?:string};
const initialItems:Item[]=[
{id:1,title:"One Piece",meta:"Chapter 1152",type:"Reading",progress:72,updated:"12 min ago",source:"2 sources merged",accent:"#6FE1C1",image:"/manus-storage/suivi-reading-scene_a0b240bb.png"},
{id:2,title:"Breaking Bad",meta:"Season 3 · Episode 7",type:"Watching",progress:34,updated:"Yesterday",source:"netflix.com",accent:"#A8B8FF",image:"/manus-storage/suivi-video-still_aebef692.png"},
{id:3,title:"The Apothecary Diaries",meta:"Episode 18",type:"Watching",progress:51,updated:"2 days ago",source:"crunchyroll.com",accent:"#D0A7FF"},
{id:4,title:"The Pragmatic Programmer",meta:"Page 147 of 352",type:"Reading",progress:41,updated:"4 days ago",source:"archive.org",accent:"#9DB8A9"}];
function Progress({value,accent="#6FE1C1"}:{value:number;accent?:string}){return <div className="progress-track"><div className="progress-fill" style={{width:`${value}%`,background:accent}}/></div>}
function TypeTag({type}:{type:Item["type"]}){return <span className="type-tag"><span className={`type-dot ${type.toLowerCase()}`}/>{type}</span>}
export default function Home(){
 const [items,setItems]=useState(initialItems),[query,setQuery]=useState(""),[filter,setFilter]=useState<"All"|"Reading"|"Watching">("All"),[checking,setChecking]=useState(false),[showConflict,setShowConflict]=useState(false),[showVideoTools,setShowVideoTools]=useState(false),[speed,setSpeed]=useState(1);
 const current=items[0]; const filtered=useMemo(()=>items.filter(i=>(filter==="All"||i.type===filter)&&`${i.title} ${i.meta}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
 const check=()=>{setChecking(true);setTimeout(()=>{setChecking(false);toast.success("You’re up to date",{description:"No new chapter or episode found."})},850)};
 const save=()=>{if(current.progress<72){setShowConflict(true);return}toast.success("Progress saved locally",{description:"Duplicate sources merged · highest position kept"})};
 const updateSpeed=(delta:number)=>{const next=Math.min(3,Math.max(.25,Number((speed+delta).toFixed(2))));setSpeed(next);toast(`Playback speed ${next}×`)};
 return <div className="premium-app"><header className="top-nav"><div className="brand"><span className="brand-mark" aria-hidden="true"><i/></span><span>suivi</span></div><nav><button className="nav-active">Library</button><button>Activity</button><button>Collections</button></nav><div className="nav-right"><button className="nav-language">EN <ChevronDown size={14}/></button><button className="nav-icon" aria-label="Notifications"><Bell size={17}/><i/></button><button className="avatar">H</button></div></header>
 <main className="dashboard"><div className="welcome-row"><div><span className="overline">YOUR PERSONAL CONTINUITY</span><h1>Continue where you left off.</h1><p>Everything you were reading and watching, in one quiet place.</p></div><button className={`update-button ${checking?"loading":""}`} onClick={check} disabled={checking}><RefreshCw size={16}/>{checking?"Checking":"Find what’s next"}</button></div>
 <section className="resume-card"><div className="resume-content"><div className="status-line"><span className="live-pulse"/>RESUME NEXT <span className="status-divider"/>96% DETECTED</div><div className="resume-title-row"><div><h2>{current.title}</h2><p>{current.meta}<span> · </span>{current.type}<span> · </span>{current.source}</p></div><button className="more-button"><MoreHorizontal size={19}/></button></div><div className="resume-progress"><Progress value={current.progress}/><div><strong>{current.progress}%</strong><span>Last saved {current.updated}</span></div></div><div className="resume-actions"><button className="continue-button" onClick={()=>toast("Opening your saved page…")}><Play size={16} fill="currentColor"/>Continue</button><button className="secondary-button" onClick={save}><Bookmark size={16}/>Save progress</button></div></div><div className="resume-image"><img src={current.image} alt="Current reading"/><div className="image-overlay"/><span>CHAPTER 1152</span></div></section>
 <div className="content-grid"><section className="library-card"><div className="card-heading"><div><span className="overline">YOUR LIBRARY</span><h3>All progress</h3></div><div className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search library"/></div></div><div className="tabs">{(["All","Reading","Watching"] as const).map(t=><button className={filter===t?"active":""} onClick={()=>setFilter(t)} key={t}>{t}<span>{t==="All"?items.length:items.filter(i=>i.type===t).length}</span></button>)}</div><div className="list">{filtered.map(item=><article className="progress-row" key={item.id}><div className="item-avatar" style={{background:item.accent,color:"#07131D"}}>{item.title[0]}</div><div className="row-main"><div className="row-title"><h4>{item.title}</h4><TypeTag type={item.type}/></div><p>{item.meta}</p><div className="row-bar"><Progress value={item.progress} accent={item.accent}/><span>{item.progress}%</span></div></div><div className="row-source"><strong>{item.source}</strong><span>{item.updated}</span></div><button className="row-delete" onClick={()=>{setItems(prev=>prev.filter(i=>i.id!==item.id));toast("Removed from your library")}}><Trash2 size={15}/></button></article>)}</div><button className="add-row" onClick={()=>toast("Open a page and Suivi will detect it")}> <Plus size={16}/> Keep something in motion</button></section>
 <aside className="insight-card"><div className="card-heading"><div><span className="overline">ON THIS PAGE</span><h3>One Piece</h3></div><span className="synced"><Check size={13}/>Synced</span></div><div className="source-chip"><span className="source-logo">M+</span><div><strong>Chapter 1152</strong><span>Detected from structured data</span></div></div><div className="insight-section"><span className="overline">AVAILABILITY</span><button className="outline-action" onClick={check}><Bell size={15}/>Look for what’s next<ChevronDown size={14}/></button><small>Manual check · no background tracking</small></div><div className="insight-section"><span className="overline">VIDEO TOOLS</span><button className="outline-action" onClick={()=>setShowVideoTools(v=>!v)}><Video size={15}/>Picture-in-Picture & speed <b>{showVideoTools?"−":"+"}</b></button>{showVideoTools&&<div className="video-controls"><div className="speed-line"><span>Playback speed</span><div><button onClick={()=>updateSpeed(-.25)}><Minus size={15}/></button><strong>{speed}×</strong><button onClick={()=>updateSpeed(.25)}><Plus size={15}/></button></div></div><button className="pip-action" onClick={()=>toast("PiP requested for the active video")}>Open Picture-in-Picture</button></div>}</div><div className="privacy-line"><span className="privacy-dot"/>Stored locally · no account required</div></aside></div></main>
 {showConflict&&<div className="modal-backdrop"><div className="conflict-modal"><button className="modal-close" onClick={()=>setShowConflict(false)}><X size={17}/></button><div className="conflict-icon"><RefreshCw size={18}/></div><span className="overline">PROGRESS CONFLICT</span><h2>Keep the higher position?</h2><p>Another source has a lower position for <strong>One Piece</strong>. Your saved Chapter 100 is safer to keep.</p><div className="conflict-actions"><button className="secondary-button" onClick={()=>setShowConflict(false)}>Keep Chapter 100</button><button className="continue-button" onClick={()=>{setShowConflict(false);toast.success("Progress replaced")}}>Replace it</button></div></div></div>}
 </div>}
