/* Dasi pastel media library: airy white canvas, soft lilac/mint/sky cards, image-first rails, friendly minimal logo. */
import { useMemo, useState } from "react";
import { Bell, Bookmark, Check, ChevronRight, Film, Grid2X2, Heart, History, Library, Minus, Play, Plus, RefreshCw, Search, Settings2, Sparkles, Trash2, Video, X } from "lucide-react";
import { toast } from "sonner";
type Item={id:number;title:string;meta:string;type:"Reading"|"Watching";progress:number;updated:string;source:string;accent:string;image?:string;tag?:string};
const itemsSeed:Item[]=[
{id:1,title:"One Piece",meta:"Chapter 1152",type:"Reading",progress:72,updated:"12 min ago",source:"2 sources merged",accent:"#D9F4EA",image:"/manus-storage/one-piece-cover_6094f10e.jpeg",tag:"Continue"},
{id:2,title:"Breaking Bad",meta:"Season 3 · Episode 7",type:"Watching",progress:34,updated:"Yesterday",source:"netflix.com",accent:"#DDE7FF",image:"/manus-storage/breaking-bad-poster_30f4862f.jpg",tag:"Watching"},
{id:3,title:"The Apothecary Diaries",meta:"Episode 18",type:"Watching",progress:51,updated:"2 days ago",source:"crunchyroll.com",accent:"#F0DFFF",image:"/manus-storage/apothecary-diaries_cd79dc6f.jpg",tag:"Watching"},
{id:4,title:"The Pragmatic Programmer",meta:"Page 147 of 352",type:"Reading",progress:41,updated:"4 days ago",source:"archive.org",accent:"#FFE7D6",tag:"Reading"}];
function Progress({value,accent="#6CBE9E"}:{value:number;accent?:string}){return <div className="progress-track"><div className="progress-fill" style={{width:`${value}%`,background:accent}}/></div>}
function Pill({children,active=false,onClick}:{children:React.ReactNode;active?:boolean;onClick?:()=>void}){return <button onClick={onClick} className={`category-pill ${active?"active":""}`}>{children}</button>}
export default function Home(){
 const [items,setItems]=useState(itemsSeed),[filter,setFilter]=useState<"All"|"Reading"|"Watching">("All"),[query,setQuery]=useState(""),[checking,setChecking]=useState(false),[speed,setSpeed]=useState(1),[tools,setTools]=useState(false),[conflict,setConflict]=useState(false);
 const current=items[0];const filtered=useMemo(()=>items.filter(i=>(filter==="All"||i.type===filter)&&`${i.title} ${i.meta}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
 const check=()=>{setChecking(true);setTimeout(()=>{setChecking(false);toast.success("Tout est à jour",{description:"Aucun nouveau chapitre ou épisode détecté."})},800)};
 const save=()=>{if(current.progress<72){setConflict(true);return}toast.success("Progression mémorisée")};
 return <div className="dasi-app"><header className="dasi-header"><div className="dasi-brand"><span className="dasi-logo"><i/></span><span className="shine">Dasi</span></div><nav><button className="active">Ma bibliothèque</button><button>Découvrir</button><button>Collections</button></nav><div className="header-actions"><div className="header-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une œuvre"/></div><button className="header-icon"><Bell size={18}/><i/></button><button className="profile">H</button></div></header>
 <main className="dasi-main"><div className="welcome"><div><span className="eyebrow pastel-label">TON ESPACE DE REPRISE</span><h1>On reprend où ?</h1><p>Ta bibliothèque garde la trace de ce que tu lis et regardes.</p></div><button className="refresh-button" onClick={check} disabled={checking}><RefreshCw size={16}/>{checking?"Vérification…":"Vérifier les nouveautés"}</button></div>
 <section className="dasi-hero"><div className="hero-soft-shape shape-one"/><div className="hero-soft-shape shape-two"/><div className="hero-details"><div className="hero-chip"><Sparkles size={14}/> Ta prochaine reprise</div><h2>{current.title}</h2><p>{current.meta}<span> · </span>{current.type}</p><div className="hero-progress"><Progress value={current.progress}/><strong>{current.progress}%</strong></div><small>Enregistré il y a {current.updated}</small><div className="hero-buttons"><button className="primary-cta" onClick={()=>toast("Ouverture de ta page enregistrée…")}><Play size={16} fill="currentColor"/>Reprendre</button><button className="heart-button" onClick={save}><Bookmark size={17}/>Garder ma position</button></div></div><div className="hero-art"><img src={current.image} alt="Couverture de One Piece"/><div className="art-wash"/><span>CH. 1152</span></div></section>
 <div className="quick-categories"><Pill active={filter==="All"} onClick={()=>setFilter("All")}><Grid2X2 size={15}/>Tout <b>{items.length}</b></Pill><Pill active={filter==="Reading"} onClick={()=>setFilter("Reading")}><Library size={15}/>À lire <b>{items.filter(i=>i.type==="Reading").length}</b></Pill><Pill active={filter==="Watching"} onClick={()=>setFilter("Watching")}><Film size={15}/>À regarder <b>{items.filter(i=>i.type==="Watching").length}</b></Pill><Pill><History size={15}/>Activité</Pill></div>
 <section className="rail-section"><div className="rail-title"><div><span className="eyebrow">REPRENDRE</span><h3>Ta file d’attente</h3></div><button>Voir tout <ChevronRight size={16}/></button></div><div className="cover-rail">{filtered.slice(0,3).map(item=><article className="cover-card" key={item.id} onClick={()=>toast(`Position ouverte : ${item.meta}`)}><div className="cover-image" style={{background:item.accent}}>{item.image?<img src={item.image} alt=""/>:<span>{item.title[0]}</span>}<span className="cover-badge">{item.tag}</span></div><div className="cover-info"><h4>{item.title}</h4><p>{item.meta}</p><Progress value={item.progress} accent={item.accent==="#DDE7FF"?"#8EA8E7":"#6CBE9E"}/><small>{item.progress}% · {item.updated}</small></div></article>)}</div></section>
 <div className="lower-grid"><section className="progress-panel"><div className="rail-title"><div><span className="eyebrow">BIBLIOTHÈQUE</span><h3>Tout suivre au même endroit</h3></div><button onClick={check}>Nouveautés <RefreshCw size={14}/></button></div><div className="mini-tabs">{(["All","Reading","Watching"] as const).map(t=><button className={filter===t?"selected":""} onClick={()=>setFilter(t)} key={t}>{t==="All"?"Tout":t==="Reading"?"À lire":"À regarder"}</button>)}</div><div className="dasi-list">{filtered.map(item=><article className="dasi-row" key={item.id}><div className="row-cover" style={{background:item.accent}}>{item.image?<img src={item.image} alt=""/>:<span>{item.title[0]}</span>}</div><div className="dasi-row-main"><div><h4>{item.title}</h4><span className="row-type">{item.type}</span></div><p>{item.meta}</p><div className="row-progress"><Progress value={item.progress} accent={item.accent==="#DDE7FF"?"#8EA8E7":"#6CBE9E"}/><small>{item.progress}%</small></div></div><div className="row-source"><span>{item.source}</span><small>{item.updated}</small></div><button className="delete-row" onClick={()=>{setItems(prev=>prev.filter(i=>i.id!==item.id));toast("Retiré de ta bibliothèque")}}><Trash2 size={15}/></button></article>)}</div></section><aside className="now-panel"><div className="now-head"><div><span className="eyebrow">SUR CETTE PAGE</span><h3>One Piece</h3></div><span className="synced"><Check size={13}/>à jour</span></div><div className="detected-box"><div className="mini-cover"><img src={current.image} alt=""/></div><div><strong>Chapter 1152</strong><span>Détecté sur la page ouverte</span></div></div><button className="soft-action" onClick={check}><RefreshCw size={15}/>Voir s’il y a du nouveau<ChevronRight size={15}/></button><button className="soft-action" onClick={()=>setTools(v=>!v)}><Video size={15}/>Outils vidéo <b>{tools?"−":"+"}</b></button>{tools&&<div className="video-pop"><div><span>Vitesse</span><div className="speed"><button onClick={()=>setSpeed(Math.max(.25,speed-.25))}><Minus size={14}/></button><strong>{speed}×</strong><button onClick={()=>setSpeed(Math.min(3,speed+.25))}><Plus size={14}/></button></div></div><button className="pip-cta" onClick={()=>toast("Picture-in-Picture demandé")}>Ouvrir Picture-in-Picture</button></div>}<div className="local-note"><Heart size={14}/>Tout reste sur ton appareil</div></aside></div></main>
 {conflict&&<div className="modal-backdrop"><div className="conflict-modal"><button className="modal-close" onClick={()=>setConflict(false)}><X size={17}/></button><span className="eyebrow">PETIT CONFLIT DE POSITION</span><h2>Garder le chapitre le plus avancé ?</h2><p>Une autre source indique une position différente pour <strong>One Piece</strong>. Ta position enregistrée reste prioritaire.</p><div className="conflict-actions"><button className="heart-button" onClick={()=>setConflict(false)}>Garder ma position</button><button className="primary-cta" onClick={()=>{setConflict(false);toast.success("Position remplacée")}}>Remplacer</button></div></div></div>}
 </div>}
