import {useEffect,useRef,useState} from 'react';
import {toast} from 'sonner';
import {useStore} from '@/store/StoreContext';
import {useI18n} from '@/i18n/I18nContext';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function ProfileEditor(){
 const store=useStore(),{lang}=useI18n(),fr=lang==='fr',profile=store.profile||{};
 const [crop,setCrop]=useState<{image:ImageBitmap;kind:'avatar'|'banner'}>(),[zoom,setZoom]=useState(1),[x,setX]=useState(0),[y,setY]=useState(0),canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{if(!crop||!canvas.current)return;const c=canvas.current,w=c.width,h=c.height,ctx=c.getContext('2d')!;const scale=Math.max(w/crop.image.width,h/crop.image.height)*zoom,iw=crop.image.width*scale,ih=crop.image.height*scale;ctx.clearRect(0,0,w,h);ctx.drawImage(crop.image,(w-iw)/2+x*(iw-w)/2,(h-ih)/2+y*(ih-h)/2,iw,ih);},[crop,zoom,x,y]);
 useEffect(()=>()=>crop?.image.close(),[crop]);
 const pick=async(file:File|undefined,kind:'avatar'|'banner')=>{if(!file)return;try{if(file.size>10000000||!/^image\/(png|jpeg|webp)$/.test(file.type))throw Error();const image=await createImageBitmap(file);if(image.width*image.height>40000000){image.close();throw Error();}setZoom(1);setX(0);setY(0);setCrop({image,kind});}catch{toast.error(fr?'Choisissez une image PNG, JPEG ou WebP de moins de 10 Mo.':'Choose a PNG, JPEG or WebP image under 10 MB.');}};
 return <section className="settings-card profile-editor"><h2>{fr?'Mon profil':'My profile'}</h2>{profile.banner&&<img className="profile-banner" src={profile.banner} alt=""/>}<div className="profile-fields">{profile.avatar&&<img className="profile-photo" src={profile.avatar} alt=""/>}<label>{fr?'Nom affiché':'Display name'}<input key={profile.name} defaultValue={profile.name||''} maxLength={100} onBlur={e=>store.updateProfile({name:e.target.value})}/></label><label>{fr?'Biographie':'Biography'}<textarea key={profile.bio} defaultValue={profile.bio||''} maxLength={2000} rows={3} onBlur={e=>store.updateProfile({bio:e.target.value})}/></label></div><div className="settings-actions">{(['avatar','banner'] as const).map(kind=><div key={kind}><label className="refresh-button">{kind==='avatar'?'Avatar':fr?'Bannière':'Banner'}<input aria-label={kind==='avatar'?'Avatar':fr?'Bannière':'Banner'} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void pick(e.target.files?.[0],kind);e.target.value='';}}/></label>{profile[kind]&&<button onClick={()=>store.updateProfile({[kind]:''})}>{fr?'Retirer':'Remove'}</button>}</div>)}</div>
 {crop&&<Dialog open onOpenChange={open=>!open&&setCrop(undefined)}><DialogContent><DialogTitle>{fr?'Recadrer l’image':'Crop image'}</DialogTitle><DialogDescription>{fr?'Ajustez le zoom et la position avant d’enregistrer.':'Adjust zoom and position before saving.'}</DialogDescription><canvas ref={canvas} width={crop.kind==='avatar'?512:1600} height={crop.kind==='avatar'?512:400} style={{width:'100%',maxHeight:400,objectFit:'contain',borderRadius:crop.kind==='avatar'?'50%':12}}/>{[['Zoom',zoom,setZoom,1,3],['Horizontal',x,setX,-1,1],['Vertical',y,setY,-1,1]].map(([label,value,set,min,max])=><label key={String(label)}>{String(label)}<input type="range" min={Number(min)} max={Number(max)} step={0.01} value={Number(value)} onChange={e=>(set as (n:number)=>void)(Number(e.target.value))}/></label>)}<button className="primary-cta" onClick={()=>{if(!canvas.current)return;store.updateProfile({[crop.kind]:canvas.current.toDataURL('image/webp',0.85)});setCrop(undefined);toast.success(fr?'Image enregistrée':'Image saved');}}>{fr?'Enregistrer l’image':'Save image'}</button></DialogContent></Dialog>}
 </section>;
}
